name: Publish to PyPI
on:
  release:
    types: [published]

jobs:
  pypi_release:
    name: Builds Using Poetry and Publishes to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - run: poetry config pypi-token.pypi "${{ secrets.PYPI_API_KEY }}"
    - name: Publish package
      run: poetry publish --build
