name: Publish to Test PyPI
on:
  push:
    tags:
    - '*.*.*'

jobs:
  test_pypi_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with dev
    - name: Run unit tests
      run: poetry run python -m unittest discover
    - run: poetry config repositories.testpypi https://test.pypi.org/legacy/
    - run: poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_API_KEY }}
    - name: Publish package
      run: poetry publish --build -r testpypi
